alias h='history -f'
alias hg='history -f | grep -i'
alias nocolor='sed "s/\x1B\[[0-9;]*[mGK]//g"'
alias www='python3 -m http.server'
alias ports='netstat -tulanp'
alias urlenc='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])"'
alias urldec='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'